const fs = require('fs');
const YAML = require('yaml');
const axios = require('axios');

module.exports = (basicMessage, msgsArray, templateName) => new Promise((resolve, reject) => {
const rawConfig = fs.readFileSync(`${__dirname}/../../configs/config.yml`, 'utf-8');
    const config = YAML.parse(rawConfig);

    if (config.config.slack && config.config.slack.webhook) {
        const msgBlock = {
            text: basicMessage,
            blocks: [{
                type: "section",
                text: {
                    type: "mrkdwn",
                    text: `*Errors occurred when running the template "${templateName}".*`
                }
            }]
        };
    
        for (let idx in msgsArray) {
            const msg = msgsArray[idx];
            msgBlock.blocks.push({
                type: "section",
                text: {
                    type: "mrkdwn",
                    text: msg
                }
            });
        }
    
        msgBlock.blocks.push({
            type: "section",
            text: {
                type: "mrkdwn",
                text: `Please review the PDF document generated by the SysDiag application regarding this test.`
            }
        });
    
        axios.post(config.config.slack.webhook, msgBlock).then(() => resolve()).catch(() => resolve());
    } else {
        console.log("[INFO] There is no slack configuration! Skipping the report.");
        resolve();
    }

});