const fs = require('fs');
const YAML = require('yaml');
const axios = require('axios');

module.exports = (basicMessage, msgsArray, _) => new Promise((resolve, reject) => {
    // we load the core configuration file
    const rawConfig = fs.readFileSync(`${__dirname}/../../../configs/config.yml`, 'utf-8');
    const config = YAML.parse(rawConfig);

    // if we have a google chat configuration section and a webhook defined, we will proceed to craft the payload
    if (config.config.google_chat && config.config.google_chat.webhook) {
        // message head
        const msgBlock = {
            text: `${basicMessage}\n\nTests:\n${(msgsArray.join('\n'))}\n\nPlease review the PDF document generated by the SysDiag application regarding this test.`
        };
    
        // we send the payload over to the google chat servers...
        axios.post(config.config.google_chat.webhook, msgBlock).then(() => resolve()).catch(() => resolve());
    } else {
        resolve();
    }

});