template:
  name: OWS - Development
  type: ec2
  region: eu-west-3
  tags:
    - name: Alias
      value: offing-develop
  auth:
    user: ec2-user
    key: aws-develop-20200309.pem
    port: 22
  actions:
    - name: root storage under 80%
      type: command
      command: df -h / | tail -n1 | tr -s " " | cut -f5 -d" " | tr -d "%"
      expected_output:
        type: max_value
        limit: 80
    - name: update os
      type: command
      command: sudo yum update -y
    - name: cpu usage below 80%
      type: cloudwatch
      metric: CPUUtilization
      expected_output:
        type: below
        value: 80
        measure: percent
    - name: cpu credits above 80 units
      type: cloudwatch
      metric: CPUCreditBalance
      expected_output:
        type: above
        value: 80
        measure: units
    - name: apache is running
      type: command
      command: sudo service httpd status
      expected_output:
        type: pattern
        value: active (running)
    - name: apache syntax
      type: command
      command: sudo apachectl configtest 2>&1
      expected_output:
        type: match
        value: Syntax OK
    - name: web directories owners
      type: command
      command: sudo ls -l /var/www/html/ | grep -v apache | grep -v "^total"
      expected_output:
        type: empty
